### ISSUE TITLE
Add opt-in/out feature for ci tests

### ISSUE THREAD

**Issue by ghost** [thefederationinfo/github-integration#4]
> Also I don’t know if there should be something like [ci skip] for it, or maybe even the opposite, run only when there is [federation] or a federation-label at the PR (as a setting per repo if default on or off). Because there are also many frontend PRs which would only add unnecessary load to travis. And while I would have it enabled by default for the federation repos, I would have it default-off for the diaspora-repo (because most PRs there are not related to federation, only when updating the federation lib or some refactorings, it would be interesting to run the tests there too).

related to https://sechat.org/posts/3581013#45b550300a0e0136176b52540061b601

**Comment by ghost** [comment]
Just saw that the current PR webhook also reports labeled and unlabeled events.
I would say we create a third field after authentication:

1) Project name 2) Project slug and 3) (optional) Label

If label is empty the server will trigger builds on every PR creation event if not wait for the right label to appear.

**Comment by SuperTux88** [comment]
That sounds like a great solution :+1: 

For the opt-out it's probably enough to just handle the `[ci skip]` like on travis, which would be present on commits which don't contain code-changes anyway to skip travis, like for example documentation-changes or other small changes that don't need ci.
