### ISSUE TITLE
Displayed name of the testsuite in a pull request

### ISSUE THREAD

**Issue by ghost** [thefederationinfo/github-integration#7]
Currently the server will show up as `Federation Suite` like in this example: ![https://socialhome.network/media/uploads/2018/03/12/d457fbc0-636e-4b5f-96e9-a8b43bfdfae3.png](https://socialhome.network/media/uploads/2018/03/12/d457fbc0-636e-4b5f-96e9-a8b43bfdfae3.png)

But all the current implementations like Travis, codedov and so on.. are using a format like this:
`continuous-integration/travis-ci/pr`

Shall we do the same? How should that look like?

`continuous-integration/thefederation/pr`

**Comment by jaywink** [comment]
Hmm don't see why myself, I like how it is at the moment :+1:
